services:
  api:
    # name of container
    container_name: 'acquisitions-api'
    # name of image
    image: acquisitions-api:1.0
    # environment variables

    build:
      context: .
      dockerfile: dockerfile

    # port
    ports:
      - '3000:3000'

    # adding env file for local development
    env_file:
      - .env

    # restart policy
    restart: unless-stopped

    # healthcheck
    healthcheck:
      test: ['CMD-SHELL', 'wget -qO- http://localhost:3000/health || exit 1']
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
