name : CI pipeline

# start when the event push or pull-request on the branch main or master
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs : 
# check the quality of code and dependencies
  quality-check : 
    # run on the ubuntu latest version
    runs-on: ubuntu-latest
    # steps
    steps :

      - name : Checkout reponsitory
        #Checkout the code from the repository
        uses: actions/checkout@v4

      - name : Setup pnpm
        #Setup the pnpm environment
        uses: pnpm/action-setup@v4
      - name : Setup Node.js 22
        #Setup the node.js 22 environment
        uses: actions/setup-node@v4
      - name : Install dependencies
        run : pnpm i --frozen-lockfile

      - name : run linter
        run : pnpm lint

      - name : check code formating
        run : pnpm format:check

# job 2 : checked package build
  docker-build-test:
    name : docker build & verify
    needs: quality-check
    runs-on: ubuntu-latest
    # steps
    steps :
      - name : checkout reponsitory
        uses : actions/checkout@v4
    
      - name : set up docker buildx
        uses : docker/setup-buildx-action@v3 # a repo allow to use docker without sudo

      - name : build docker imgae
        run : |
          docker build -t acquisitions-api:test .